In [ ]:
import numpy as np

In [ ]:
data = np.array([[1,2,3,4,5],[1,2,3,4,5]],dtype=int)

In [ ]:
print(data)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
data.shape

(2, 5)

In [ ]:
type(data)

numpy.ndarray

In [ ]:
print(len(data))

2


In [ ]:
print(data.ndim)

2


In [ ]:
a1 = data.reshape(10,1)

In [ ]:
a2 = data.reshape(1,10)

In [ ]:
a1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
a2

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [ ]:
a3 = data.reshape(1,-1)
a3

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [ ]:
a3.ndim

2

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,0]
list3 = [4,5,6,7,8]
mul_l = np.array([list1,list2,list3], dtype = int)


In [ ]:
mul_l

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [4, 5, 6, 7, 8]])

In [ ]:
mul_l.shape

(3, 5)

In [ ]:
mul_l = mul_l.reshape(5,3)

In [ ]:
mul_l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 4, 5],
       [6, 7, 8]])

In [ ]:
mul_l.shape

(5, 3)

In [ ]:
mul_l.shape = (3,5)

In [ ]:
mul_l

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [4, 5, 6, 7, 8]])

In [ ]:
list4 = [2,4,5,'6']
list5 = [3,4,5,6]
mul_l_test = np.array([list4,list5], dtype = int)

In [ ]:
mul_l_test

array([[2, 4, 5, 6],
       [3, 4, 5, 6]])

In [ ]:
b1 = np.arange(24)
b1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
b1.shape

(24,)

In [ ]:
b1.ndim

1

In [ ]:
b1.reshape(2,6,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
b1.reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
x = np.array([2,3,4,5], dtype = np.int8)
x.itemsize

1

In [ ]:
x = np.array([2,3,4,5], dtype = np.int32)
x.itemsize

4

In [ ]:
x = np.array([2,3,4,5], dtype = np.int64)
x.itemsize

8

In [ ]:
y = np.array([1.223434,2,3,4,5],dtype = np.float64)
y

array([1.22, 2.  , 3.  , 4.  , 5.  ])

In [ ]:
np.set_printoptions(precision = 2)

In [ ]:
y

array([1.22, 2.  , 3.  , 4.  , 5.  ])