In [2]:
lst  = [2,54,3,5,7,4]
lst

[2, 54, 3, 5, 7, 4]

In [3]:
#1-D arary
import numpy as np
lst  = np.array([2,4,5,6,7])
print(lst)

[2 4 5 6 7]


In [4]:
#2-D array
lst = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(lst)
import pandas as pd
df = pd.DataFrame(lst)
df

[[1 2 3 4 5]
 [6 7 8 9 0]]


0  1  2  3  4
0  1  2  3  4  5
1  6  7  8  9  0

In [5]:
#3-D array
lst = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,0]]])
print(lst)


[[[1 2 3 4]
  [4 5 6 7]
  [7 8 9 0]]]


In [6]:
type(lst)

numpy.ndarray

In [7]:
print(lst.size)

12


In [8]:
lst.shape

(1, 3, 4)